name: 'size'
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: andresz1/size-limit-action@v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
